import os
import re
from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.utilities import SQLDatabase
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
from src.llm import LlmModel
from src.kafka_utils.connection_manager import KafkaConnectionManager
from src.kafka_utils.config import TOPICS
import logging
import uuid

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


db_uri = os.getenv("DB_URI")
db = SQLDatabase.from_uri(db_uri)

print("💬 Ask your question (type 'exit' to quit):")

def get_schema(_):
    return db.get_table_info()

def get_prompt():
    template = """
    Based on the table schema below, write ONLY the SQL query. Do not include any explanations, comments, or additional text after the query. End the query with a semicolon.
    
    IMPORTANT BUSINESS LOGIC RULES:
    
    1. DETECT ACTION vs CHECK:
       - If the question asks to "cancel", "execute cancellation", "process cancellation", "refund", "execute refund", "process refund" → Generate UPDATE/INSERT queries (ACTION)
       - If the question asks "can be cancelled", "is it possible to cancel", "check if can cancel" → Generate SELECT query (CHECK)
    
    2. For ACTION queries (actually cancelling/refunding an order):
       - First, UPDATE lg_orders SET order_status = 'Cancelled' WHERE order_id = X; (for cancellation)
       - Then, INSERT INTO lg_order_cancellation (order_id, reason, cancelled_by) VALUES (X, 'Customer request', 'system');
       - For refunds: 
         * First, get the order's total_amount: SELECT total_amount FROM lg_orders WHERE order_id = X;
         * Then, UPDATE lg_orders SET order_status = 'Refunded' WHERE order_id = X;
         * Then, INSERT INTO lg_refunds (order_id, refund_amount, refund_status) VALUES (X, <total_amount_from_order>, 'Completed');
       - IMPORTANT for refunds: 
         * You MUST use the actual total_amount value from the lg_orders table
         * Use a subquery: INSERT INTO lg_refunds (order_id, refund_amount, refund_status) VALUES (X, (SELECT total_amount FROM lg_orders WHERE order_id = X), 'Completed');
         * OR use the actual numeric value if you know it
         * NEVER use placeholders like ? or $1 in raw SQL - use actual values or subqueries
       - Generate BOTH queries separated by semicolon
       - IMPORTANT: 
         * Do NOT include SERIAL/auto-increment columns (like cancel_id, refund_id) in INSERT statements
         * These columns will be auto-generated by the database
         * Only include: order_id, reason, cancelled_by for cancellations
         * Only include: order_id, refund_amount, refund_status for refunds
       - Ensure all parentheses are properly closed in VALUES clauses
       - Example: VALUES (32, 'Customer request', 'system'); NOT VALUES (32, 'Customer request', 'system';
       - Always end each statement with a semicolon
       - NEVER use SQL parameter placeholders (?, $1, etc.) - use actual values or subqueries
    
    3. For CHECK queries (checking if order can be cancelled/refunded):
       - First check if the order EXISTS in the lg_orders table (this is the source of truth)
       - Check the order_status in lg_orders table
       - Check if a cancellation record exists in lg_order_cancellation table (LEFT JOIN)
       - Check if a refund record exists in lg_refunds table (LEFT JOIN)
       - An order CAN be cancelled if:
         * It exists in lg_orders
         * Its order_status is NOT 'Cancelled' or 'Refunded'
         * There is NO record in lg_order_cancellation for that order_id
         * There is NO record in lg_refunds for that order_id
       - Use LEFT JOINs to check all these conditions in one query
       - Return the order details along with cancellation/refund status
       - For LEFT JOINs: join ONLY on the key column (e.g., order_id), do NOT add WHERE conditions in the JOIN clause
       - Example: LEFT JOIN lg_order_cancellation ON lg_orders.order_id = lg_order_cancellation.order_id
       - Use CASE statements or IS NULL checks in SELECT to determine if cancellation/refund exists
       - DO NOT use string literals like 'N/A' for TIMESTAMP or DATE columns in COALESCE
       - For TIMESTAMP/DATE columns: use NULL, or CAST to text first: COALESCE(column::text, 'N/A')
       - Better approach: use CASE WHEN column IS NULL THEN 'Not Cancelled' ELSE 'Cancelled' END
    
    4. For general existence checks:
       - Query the PRIMARY table (e.g., lg_orders for orders, lg_customers for customers)
       - Return the actual data/rows if the record exists
       - Use proper WHERE clauses to filter by the specified IDs or conditions
    
    5. Always query the main/primary table first, not the related tables (cancellation, refunds) to check existence.
    
    6. SQL TYPE SAFETY:
       - Never use string literals like 'N/A' for numeric, date, or timestamp columns
       - Use NULL for missing values in typed columns
       - If you need to show text for missing values, use CASE statements that return text
    
    {schema}

    Question: {question}
    
    SQL Query:
    """
    return ChatPromptTemplate.from_template(template)


llm = LlmModel.get_llm()

# Extract SQL text only
def extract_sql(text):
    return text.strip().split("SQL Query:")[-1].strip()


def clean_sql(query: str) -> str:
    """
    Clean and extract SQL query from LLM response.
    Handles cases where LLM includes explanatory text after the SQL query.
    Also fixes common SQL type errors and JOIN clause issues.
    Preserves multiple SQL statements separated by semicolons.
    """
    # Remove markdown code blocks
    q = query.strip()
    q = q.replace("```sql", "").replace("```", "").strip()
    
    import re
    
    # Split by semicolons to handle multiple statements
    # But be careful - semicolons can appear in string literals
    statements = []
    current_pos = 0
    in_string = False
    string_char = None
    
    # Simple parser to split by semicolons while respecting string literals
    for i, char in enumerate(q):
        if char in ("'", '"') and (i == 0 or q[i-1] != '\\'):
            if not in_string:
                in_string = True
                string_char = char
            elif char == string_char:
                in_string = False
                string_char = None
        elif char == ';' and not in_string:
            statement = q[current_pos:i+1].strip()
            if statement:
                statements.append(statement)
            current_pos = i + 1
    
    # Add the last statement if there's no trailing semicolon
    if current_pos < len(q):
        statement = q[current_pos:].strip()
        if statement:
            statements.append(statement)
    
    # If no semicolons found, treat as single statement
    if not statements:
        statements = [q]
    
    # Clean each statement
    cleaned_statements = []
    for stmt in statements:
        stmt = stmt.strip()
        if not stmt:
            continue
        
        # Remove any trailing explanatory text
        # Look for patterns that indicate end of SQL (e.g., text starting with capital letter)
        lines = stmt.split('\n')
        sql_lines = []
        for line in lines:
            line_stripped = line.strip()
            # Stop if we hit explanatory text (starts with capital, not SQL keyword)
            if line_stripped and not re.match(r'^\s*(UPDATE|INSERT|SELECT|DELETE|CREATE|ALTER|DROP|WITH|FROM|WHERE|SET|VALUES|INTO|JOIN|ON|AND|OR|ORDER|GROUP|HAVING|LIMIT)', line_stripped, re.IGNORECASE):
                if re.match(r'^[A-Z][a-z]', line_stripped):  # Starts with capital letter
                    break
            sql_lines.append(line)
        
        cleaned_stmt = '\n'.join(sql_lines).strip()
        
        # Don't remove the semicolon - keep it if present
        # Just ensure it ends with semicolon if it's a complete statement
        if cleaned_stmt:
            # Check if it already ends with semicolon
            if not cleaned_stmt.rstrip().endswith(';'):
                cleaned_stmt += ';'
            cleaned_statements.append(cleaned_stmt)
    
    # Join statements with space
    result = ' '.join(cleaned_statements)
    
    # Fix common SQL type errors: Replace 'N/A' in COALESCE for timestamp/date columns
    pattern = r"COALESCE\(([a-zA-Z_][a-zA-Z0-9_]*\.?[a-zA-Z0-9_]*)\s*,\s*'N/A'\)"
    
    def replace_coalesce(match):
        column = match.group(1)
        # Check if it's likely a date/timestamp column
        if any(keyword in column.lower() for keyword in ['date', 'time', 'cancel_date', 'refund_date', 'delivered_date', 'order_date']):
            # Cast to text first, then use COALESCE
            return f"COALESCE({column}::text, 'N/A')"
        return match.group(0)  # Keep original if not a date column
    
    result = re.sub(pattern, replace_coalesce, result, flags=re.IGNORECASE)
    
    # Fix JOIN clauses that have unnecessary conditions
    join_pattern = r"(LEFT JOIN\s+[a-zA-Z_][a-zA-Z0-9_]*\s+ON\s+[a-zA-Z_][a-zA-Z0-9_]*\.?[a-zA-Z0-9_]*\s*=\s*[a-zA-Z_][a-zA-Z0-9_]*\.?[a-zA-Z0-9_]*)\s+AND\s+[a-zA-Z_][a-zA-Z0-9_]*\.?[a-zA-Z0-9_]*\s+IS\s+NOT\s+NULL"
    
    def fix_join(match):
        # Remove the AND condition from JOIN clause
        return match.group(1)
    
    result = re.sub(join_pattern, fix_join, result, flags=re.IGNORECASE)
    
    # Fix SQL placeholders (?, $1, $2, etc.) - these are not valid in raw SQL
    # For refund INSERT statements, replace ? with subquery to get total_amount
    if 'refund' in result.lower() and '?' in result:
        # Find INSERT INTO lg_refunds ... VALUES (order_id, ?, ...)
        # Pattern: INSERT INTO lg_refunds (...) VALUES (order_id, ?, ...)
        refund_insert_pattern = r'INSERT\s+INTO\s+lg_refunds[^V]*VALUES\s*\((\d+)\s*,\s*\?'
        match = re.search(refund_insert_pattern, result, re.IGNORECASE | re.DOTALL)
        if match:
            order_id = match.group(1)
            subquery = f"(SELECT total_amount FROM lg_orders WHERE order_id = {order_id})"
            # Replace the ? that comes after order_id in VALUES clause
            result = re.sub(
                r'(VALUES\s*\(\d+\s*,\s*)\?',
                rf'\1{subquery}',
                result,
                flags=re.IGNORECASE
            )
            logger.info(f"Fixed placeholder in refund INSERT: replaced ? with subquery for order_id {order_id}")
        else:
            # Try a more general pattern
            if 'VALUES' in result and '?' in result:
                # Extract order_id from anywhere in the statement
                order_id_match = re.search(r'order_id\s*=\s*(\d+)', result, re.IGNORECASE)
                if order_id_match:
                    order_id = order_id_match.group(1)
                    subquery = f"(SELECT total_amount FROM lg_orders WHERE order_id = {order_id})"
                    result = result.replace('?', subquery, 1)
                    logger.info(f"Fixed placeholder in refund INSERT (general pattern): replaced ? with subquery for order_id {order_id}")
    
    # General placeholder removal (for other cases, just remove them or log warning)
    if '?' in result and 'refund' not in result.lower():
        logger.warning(f"Found placeholder '?' in SQL statement. This may cause errors: {result[:100]}")
    
    return result

sql_chain = (
    RunnablePassthrough.assign(schema=get_schema)
    | get_prompt()
    | llm.bind(stop=["\nSQL Result:"])
    | StrOutputParser()
    | (lambda text: clean_sql(text.strip().split("SQL Query:")[-1].strip()))
)


def get_final_prompt():
    template = """
    Based on the table schema, the question, the SQL query, and the SQL result,
    write a natural-language answer. Use ONLY the SQL result to answer the question.
    
    CRITICAL: Determine if this is a VERIFICATION (after action) or CHECK (before action) query based on the question wording.
    
    IMPORTANT INTERPRETATION RULES: 
    
    1. For ORDER CANCELLATION/REFUND VERIFICATION (after action execution):
       - KEYWORDS: "has been cancelled", "has been refunded", "Confirm the cancellation status", "Confirm the refund status"
       - If the question contains these phrases, this is a VERIFICATION query - the action was ALREADY PERFORMED
       - Check the SQL result to confirm the current state:
         * If order_status is 'Cancelled' and there's a record in lg_order_cancellation → Cancellation WAS successful (past tense)
         * If order_status is 'Refunded' and there's a record in lg_refunds → Refund WAS successful (past tense)
       - ALWAYS use past tense: "has been cancelled", "was cancelled", "has been refunded", "was refunded"
       - NEVER say "CAN be cancelled" or "CAN be refunded" for verification queries
       - Example: "Order 20 has been successfully cancelled. The order status is now 'Cancelled' and a cancellation record exists."
       - Example: "Order 13 has been cancelled. The order status is 'Cancelled' and there is a cancellation record."
    
    2. For ORDER CANCELLATION/REFUND CHECK (before action execution):
       - KEYWORDS: "can be cancelled", "can be refunded", "is it possible", "check if can"
       - If the question contains these phrases, this is a CHECK query - the action has NOT been performed yet
       - If the SQL result shows an order from lg_orders table, the order EXISTS
       - If the order exists and has no cancellation/refund records, it CAN be cancelled
       - If the order exists but already has a cancellation record, it CANNOT be cancelled (already cancelled)
       - If the order exists but already has a refund record, it CANNOT be cancelled (already refunded)
       - If the order's status is 'Cancelled' or 'Refunded', it CANNOT be cancelled
       - If the SQL result is "No rows returned", the order does NOT exist in lg_orders
    
    3. For general questions:
       - If the SQL result shows data/rows, the record EXISTS and you should answer accordingly
       - If the SQL result is "No rows returned" or empty, then the record does NOT exist
       - Be precise and accurate based on the actual SQL result
    
    4. Always base your answer on what the SQL result actually shows, not assumptions.
    5. CRITICAL: If the question says "has been cancelled/refunded" or asks to "confirm the status", use PAST TENSE and say it WAS done, not that it CAN be done.

    Schema:
    {schema}

    Question: {question}
    SQL Query: {query}
    SQL Result: {response}

    Answer:
    """
    return ChatPromptTemplate.from_template(template)


def is_action_request(question: str) -> bool:
    """Detect if the question is asking to perform an action (cancel/refund) vs just checking."""
    question_lower = question.lower()
    
    # Explicit check keywords - if these are present, it's NOT an action
    check_keywords = [
        "can be cancelled", "can it be cancelled", "is it possible",
        "check if", "verify if", "can we cancel", "is possible to cancel",
        "can i cancel", "is it cancellable", "can this be cancelled"
    ]
    
    # If it's clearly a check question, return False
    if any(check_kw in question_lower for check_kw in check_keywords):
        return False
    
    # Action keywords - if these are present and it's not a check, it's an action
    action_keywords = [
        "cancel", "execute cancellation", "process cancellation", 
        "refund", "execute refund", "process refund",
        "do cancel", "please cancel", "cancel the order",
        "process the cancellation", "go ahead and cancel",
        "proceed with cancellation", "perform cancellation"
    ]
    
    # Check for explicit action keywords
    for keyword in action_keywords:
        if keyword in question_lower:
            return True
    
    return False


def extract_order_id(question: str) -> str:
    """Extract order ID from the question."""
    import re
    # Look for patterns like "order 24", "order id 24", "order_id 24", etc.
    patterns = [
        r"order\s+(?:id\s+)?(\d+)",
        r"order_id\s+(\d+)",
        r"order\s+#?(\d+)",
        r"(\d+)"
    ]
    
    for pattern in patterns:
        match = re.search(pattern, question, re.IGNORECASE)
        if match:
            return match.group(1)
    
    return None


def fix_insert_statement(statement: str) -> str:
    """Fix INSERT statements to remove SERIAL/auto-increment columns and fix placeholders."""
    import re
    
    # Fix placeholders first (?, $1, etc.)
    # For refunds, replace ? with a subquery to get total_amount
    if 'refund' in statement.lower() and '?' in statement:
        # Extract order_id from the VALUES clause
        order_id_match = re.search(r'VALUES\s*\((\d+)', statement, re.IGNORECASE)
        if order_id_match:
            order_id = order_id_match.group(1)
            # Replace ? with subquery to get total_amount
            subquery = f"(SELECT total_amount FROM lg_orders WHERE order_id = {order_id})"
            statement = statement.replace('?', subquery)
            logger.info(f"Fixed placeholder in refund INSERT: replaced ? with subquery for order_id {order_id}")
    
    # SERIAL columns that should not be included in INSERT statements
    serial_columns = [
        'cancel_id', 'refund_id', 'tracking_id', 'item_id', 
        'account_id', 'customer_id', 'order_id'  # Only if they're SERIAL in some tables
    ]
    
    # Pattern to match INSERT INTO table (col1, col2, ...) VALUES (...)
    insert_pattern = r'INSERT\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES'
    
    match = re.search(insert_pattern, statement, re.IGNORECASE)
    if not match:
        return statement
    
    table_name = match.group(1).lower()
    columns_str = match.group(2)
    
    # Parse columns
    columns = [col.strip() for col in columns_str.split(',')]
    
    # Remove SERIAL columns based on table
    columns_to_remove = []
    if 'cancellation' in table_name:
        columns_to_remove = ['cancel_id']
    elif 'refund' in table_name and 'order' not in table_name:
        columns_to_remove = ['refund_id']
    elif 'tracking' in table_name:
        columns_to_remove = ['tracking_id']
    elif 'item' in table_name and 'order' in table_name:
        columns_to_remove = ['item_id']
    
    # Remove the columns
    filtered_columns = [col for col in columns if col.lower() not in columns_to_remove]
    
    if len(filtered_columns) != len(columns):
        # Rebuild the INSERT statement
        new_columns_str = ', '.join(filtered_columns)
        new_statement = re.sub(
            r'INSERT\s+INTO\s+\w+\s*\([^)]+\)',
            f'INSERT INTO {table_name} ({new_columns_str})',
            statement,
            flags=re.IGNORECASE
        )
        
        # Also need to remove corresponding values
        # This is trickier - we'd need to parse the VALUES clause
        # For now, just log a warning
        logger.info(f"Removed SERIAL columns from INSERT: {columns_to_remove}")
        return new_statement
    
    return statement


def validate_sql_statement(statement: str) -> tuple[bool, str]:
    """Validate SQL statement syntax and fix common issues."""
    import re
    
    stmt = statement.strip()
    original_stmt = stmt
    was_fixed = False
    
    # Fix INSERT statements first
    if re.match(r'^\s*INSERT', stmt, re.IGNORECASE):
        fixed_insert = fix_insert_statement(stmt)
        if fixed_insert != stmt:
            stmt = fixed_insert
            was_fixed = True
    
    # Count parentheses, but ignore those inside string literals
    open_parens = 0
    close_parens = 0
    in_string = False
    string_char = None
    
    for i, char in enumerate(stmt):
        if char in ("'", '"') and (i == 0 or stmt[i-1] != '\\'):
            if not in_string:
                in_string = True
                string_char = char
            elif char == string_char:
                in_string = False
                string_char = None
        elif not in_string:
            if char == '(':
                open_parens += 1
            elif char == ')':
                close_parens += 1
    
    if open_parens > close_parens:
        # Missing closing parentheses
        missing = open_parens - close_parens
        logger.warning(f"Found {missing} unmatched opening parentheses in statement")
        # Add closing parentheses before the semicolon
        if stmt.rstrip().endswith(';'):
            stmt = stmt.rstrip(';').rstrip() + ')' * missing + ';'
        else:
            stmt = stmt + ')' * missing + ';'
        logger.info(f"Fixed statement by adding {missing} closing parentheses")
        was_fixed = True
    
    # Check for unmatched quotes (simple check)
    single_quotes = stmt.count("'") - stmt.count("\\'")
    if single_quotes % 2 != 0:
        logger.warning(f"Unmatched single quotes in statement: {stmt[:100]}")
    
    return was_fixed, stmt


def execute_update_query(query: str) -> str:
    """Execute UPDATE/INSERT queries and return result.
    
    Handles multiple SQL statements separated by semicolons by executing them sequentially.
    """
    try:
        # Split query by semicolons to handle multiple statements
        # But be careful with semicolons inside string literals
        statements = []
        current_pos = 0
        in_string = False
        string_char = None
        
        # Simple parser to split by semicolons while respecting string literals
        for i, char in enumerate(query):
            if char in ("'", '"') and (i == 0 or query[i-1] != '\\'):
                if not in_string:
                    in_string = True
                    string_char = char
                elif char == string_char:
                    in_string = False
                    string_char = None
            elif char == ';' and not in_string:
                statement = query[current_pos:i+1].strip()
                if statement:
                    statements.append(statement)
                current_pos = i + 1
        
        # Add the last statement if there's no trailing semicolon
        if current_pos < len(query):
            statement = query[current_pos:].strip()
            if statement:
                statements.append(statement)
        
        # Remove empty statements
        statements = [stmt.strip() for stmt in statements if stmt.strip()]
        
        if not statements:
            return "No valid SQL statements found"
        
        logger.info(f"Executing {len(statements)} SQL statement(s)")
        results = []
        
        for idx, statement in enumerate(statements, 1):
            logger.debug(f"Original statement {idx}: {statement}")
            
            # Remove trailing semicolon for validation, we'll add it back
            statement_clean = statement.rstrip(';').strip()
            logger.debug(f"Cleaned statement {idx} (before validation): {statement_clean}")
            
            # Validate and fix the statement
            was_fixed, statement_fixed = validate_sql_statement(statement_clean)
            if was_fixed:
                logger.info(f"Fixed statement {idx}: added missing parentheses")
                logger.debug(f"Fixed statement {idx}: {statement_fixed}")
            
            # Add semicolon back if not present
            if not statement_fixed.rstrip().endswith(';'):
                statement_fixed += ';'
            
            logger.info(f"Executing statement {idx}/{len(statements)}: {statement_fixed[:100]}...")
            logger.debug(f"Full statement {idx} to execute: {statement_fixed}")
            
            try:
                # SQLDatabase.run() can execute UPDATE/INSERT queries
                raw = db.run(statement_fixed)
                logger.info(f"Statement {idx} Result (raw): {raw}")
                logger.info(f"Statement {idx} Result (type): {type(raw)}")
                
                if raw is None:
                    results.append(f"Statement {idx} executed successfully")
                elif isinstance(raw, str):
                    if not raw.strip():
                        results.append(f"Statement {idx} executed successfully")
                    else:
                        results.append(f"Statement {idx}: {raw}")
                elif isinstance(raw, (int, float)):
                    results.append(f"Statement {idx} executed successfully. {int(raw)} row(s) affected.")
                else:
                    results.append(f"Statement {idx} executed successfully. Result: {str(raw)}")
                    
            except Exception as stmt_error:
                error_str = str(stmt_error)
                error_msg = f"Error executing statement {idx}: {error_str}"
                logger.error(error_msg, exc_info=True)
                logger.error(f"Failed statement: {statement_fixed}")
                
                # Check for permission errors related to sequences
                if "permission denied for sequence" in error_str.lower() or "insufficientprivilege" in error_str.lower():
                    error_msg += "\nNote: This appears to be a database permissions issue. The database user needs permission to use the sequence for auto-increment columns. Please contact your database administrator to grant USAGE permission on the sequence."
                
                results.append(error_msg)
                # Continue with next statement even if one fails
        
        return "\n".join(results)
    except Exception as e:
        logger.error(f"Error executing UPDATE/INSERT query: {e}", exc_info=True)
        return f"Error: {str(e)}"


def run_query(query):
    """Execute SQL query and return formatted result."""
    try:
        # Check if it's an UPDATE/INSERT query
        query_upper = query.strip().upper()
        is_update_insert = (
            query_upper.startswith("UPDATE") or 
            query_upper.startswith("INSERT") or 
            query_upper.startswith("DELETE")
        )
        
        if is_update_insert:
            return execute_update_query(query)
        
        # For SELECT queries, use the original logic
        raw = db.run(query)
        logger.info(f"SQL Query Result (raw): {raw}")
        logger.info(f"SQL Query Result (type): {type(raw)}")
        logger.info(f"SQL Query Result (repr): {repr(raw)}")
        
        # Handle different result formats
        if raw is None:
            logger.warning("SQL query returned None")
            return "No results returned"
        
        # SQLDatabase.run() typically returns a string representation
        # But it might also return lists or other formats depending on the query
        if isinstance(raw, str):
            # If it's already a string, check if it's empty
            if not raw.strip():
                return "No rows returned"
            return raw
        
        # If it's like [(25,)] → convert to nice Python object
        if isinstance(raw, list):
            if len(raw) == 0:
                logger.info("SQL query returned empty list")
                return "No rows returned"
            # Return all rows, not just the first one
            formatted_rows = []
            for idx, row in enumerate(raw):
                if isinstance(row, (list, tuple)):
                    if len(row) == 1:
                        formatted_rows.append(f"Row {idx + 1}: {row[0]}")
                    else:
                        formatted_rows.append(f"Row {idx + 1}: {row}")
                else:
                    formatted_rows.append(f"Row {idx + 1}: {row}")
            result = "\n".join(formatted_rows) if len(formatted_rows) > 1 else formatted_rows[0]
            logger.info(f"Formatted SQL result: {result}")
            return result
        
        # For any other type, convert to string
        result_str = str(raw)
        logger.info(f"Converted SQL result to string: {result_str}")
        return result_str
    except Exception as e:
        logger.error(f"Error executing SQL query: {e}", exc_info=True)
        return f"Error: {str(e)}"


full_chain = (
    RunnablePassthrough.assign(query=sql_chain).assign(
        schema=get_schema,
        response=lambda vars: run_query(vars["query"])
    )
    | get_final_prompt()
    | llm
)


# -------------------------------
#      KAFKA CONNECTION MANAGER
# -------------------------------

kafka_manager = KafkaConnectionManager()

# Initialize producer connection
if not kafka_manager.connect_producer():
    logger.error("Failed to connect Kafka producer")
    exit(1)

# -------------------------------
#      INTERACTIVE LOOP
# -------------------------------

try:
    while True:
        user_question = input("\n🧑‍💻 Your Question: ")

        if user_question.lower() in ["exit", "quit"]:
            print("Goodbye! 👋")
            break

        # ------------------------------------------------------------------------------------
        # produce to kafka topic `events.input.raw`
        producer = kafka_manager.get_producer()
        if not producer:
            logger.error("Producer not available")
            continue

        print(f"Producing message to topic 'events.input.raw': {user_question}")

        message_id = str(uuid.uuid4())
        
        logger.info("")
        logger.info("🚀 [GATEWAY] New user message received")
        logger.info(f"   Message ID: {message_id}")
        logger.info(f"   User Message: {user_question}")
        logger.info(f"   Source: web_ui")
        logger.info("")
        
        event = {
            "message": user_question,
            "message_id": message_id,
            "source": "web_ui"
        }

        success = producer.produce(
            topic=TOPICS["raw_input"],
            message=event,
            key=message_id
        )
        
        if not success:
            logger.error("Failed to send message")
            continue
        
        producer.flush(timeout=5.0)

        # ------------------------------------------------------------------------------------
        # consume from kafka topic `events.input.raw`
        def handle_message(message):
            message_id = message.get("message_id", "unknown")
            logger.info("")
            logger.info("📨 [GATEWAY] Received message from pipeline")
            logger.info(f"   Message ID: {message_id}")
            logger.info(f"   Message: {message.get('message', 'unknown')}")
            logger.info(f"   Intent: {message.get('intent', 'N/A')}")
            logger.info(f"   Action: {message.get('action', 'N/A')}")
            logger.info(f"   Success: {message.get('success', False)}")
            logger.info("")
            
            # Step 1: Generate SQL
            sql_query = sql_chain.invoke({"question": user_question})
            print("\nGenerated SQL Query:")
            print(sql_query)

            # Step 2: Execute SQL and get natural answer
            answer = full_chain.invoke({"question": user_question}).content

            print("\nFinal Answer:")
            print(answer)

        # Connect consumer for this message (using unique consumer ID)
        consumer_id = f"input-consumer-{message_id}"
        if not kafka_manager.connect_consumer(
            consumer_id=consumer_id,
            group_id="gateway-consumer-group",
            topics=[TOPICS["raw_input"]],
            message_handler=handle_message,
            daemon=True
        ):
            logger.error("Failed to connect consumer")
            continue

        # Note: In a real scenario, you might want to wait for the message
        # or use a different pattern. For now, we'll process directly.
        
        # Check if this is an action request (cancel/refund) or just a check
        is_action = is_action_request(user_question)
        logger.info(f"Is action request: {is_action}")
        
        if is_action:
            # For action requests, first check if it can be done, then execute
            # Step 1: Check if order can be cancelled/refunded
            order_id = extract_order_id(user_question)
            action_type = "cancelled" if "cancel" in user_question.lower() else "refunded"
            
            if order_id:
                check_question = f"Can order {order_id} be {action_type}? Check the order status in lg_orders table and check if there are any records in lg_order_cancellation or lg_refunds tables for this order."
            else:
                check_question = f"Can this order be {action_type}? Check the order status and cancellation/refund records."
            
            logger.info(f"[ACTION REQUEST] Checking first: {check_question}")
            check_sql = sql_chain.invoke({"question": check_question})
            print("\n[CHECK] Generated SQL Query:")
            print(check_sql)
            logger.info(f"[CHECK] Generated SQL Query: {check_sql}")
            
            check_result = run_query(check_sql)
            print("\n[CHECK] SQL Query Result:")
            print(check_result)
            logger.info(f"[CHECK] SQL Query Result: {check_result}")
            
            # Step 2: If check passes, execute the action
            # Check if the result indicates it can be cancelled/refunded
            can_proceed = (
                "No rows returned" not in check_result and 
                "Error" not in check_result and
                "does NOT exist" not in check_result.lower() and
                check_result.strip() != ""
            )
            
            # Also check if there's no cancellation/refund record
            # Look for indicators that cancellation/refund already exists
            has_cancellation = (
                "Cancelled" in check_result or 
                "cancel_id" in check_result.lower() or
                "is_cancelled" in check_result.lower() and "Cancelled" in check_result
            )
            has_refund = (
                "Refunded" in check_result or 
                "refund_id" in check_result.lower() or
                "is_refunded" in check_result.lower() and "Refunded" in check_result
            )
            
            if can_proceed and not has_cancellation and not has_refund:
                # Generate and execute the action query
                logger.info(f"[ACTION REQUEST] Proceeding with {action_type} action")
                action_sql = sql_chain.invoke({"question": user_question})
                print("\n[ACTION] Generated SQL Query:")
                print(action_sql)
                logger.info(f"[ACTION] Generated SQL Query: {action_sql}")
                
                # Execute the action query (may contain multiple statements)
                action_result = run_query(action_sql)
                print("\n[ACTION] SQL Query Result:")
                print(action_result)
                logger.info(f"[ACTION] SQL Query Result: {action_result}")
                
                # Step 3: Verify the action was successful by checking the order status
                if order_id:
                    verify_question = f"Check the current status of order {order_id} in lg_orders table and check if there is a cancellation or refund record for this order."
                else:
                    verify_question = f"Check the current status of the order and check if there is a cancellation or refund record."
                
                logger.info(f"[ACTION REQUEST] Verifying action result: {verify_question}")
                verify_sql = sql_chain.invoke({"question": verify_question})
                verify_result = run_query(verify_sql)
                print("\n[VERIFY] SQL Query Result:")
                print(verify_result)
                logger.info(f"[VERIFY] SQL Query Result: {verify_result}")
                
                # Step 4: Get natural language answer based on the verification result
                # Create a question that reflects the action was performed (use past tense explicitly)
                if "cancel" in action_type:
                    answer_question = f"VERIFICATION: Order {order_id if order_id else 'the order'} has been cancelled. The cancellation action was just executed. Verify and confirm that the order status is now 'Cancelled' and that a cancellation record exists in lg_order_cancellation table. Report the current status using past tense (has been cancelled, was cancelled)."
                else:
                    answer_question = f"VERIFICATION: Order {order_id if order_id else 'the order'} has been refunded. The refund action was just executed. Verify and confirm that the order status is now 'Refunded' and that a refund record exists in lg_refunds table. Report the current status using past tense (has been refunded, was refunded)."
                
                # Use the verification result directly with the final prompt
                # Create input dict with all required fields
                verify_input = {
                    "question": answer_question,
                    "schema": get_schema({}),
                    "query": verify_sql,
                    "response": verify_result
                }
                
                # Use the final prompt chain
                verification_chain = (
                    get_final_prompt()
                    | llm
                )
                
                # Invoke with the verification data
                answer = verification_chain.invoke(verify_input).content
                
                # Prepend a success message
                if "Error" not in action_result and "Error" not in verify_result:
                    answer = f"✅ Order {order_id if order_id else 'has been'} successfully {action_type}. " + answer
            else:
                # Cannot proceed with action
                logger.warning(f"[ACTION REQUEST] Cannot proceed: can_proceed={can_proceed}, has_cancellation={has_cancellation}, has_refund={has_refund}")
                answer = full_chain.invoke({"question": check_question}).content
                if not can_proceed:
                    answer += "\n\nNote: The action cannot be performed because the order does not exist."
                elif has_cancellation or has_refund:
                    answer += "\n\nNote: The action cannot be performed because the order is already cancelled or refunded."
        else:
            # Just a check query, proceed normally
            # Step 1: Generate SQL
            sql_query = sql_chain.invoke({"question": user_question})
            print("\nGenerated SQL Query:")
            print(sql_query)
            logger.info(f"Generated SQL Query: {sql_query}")

            # Step 2: Execute SQL and get result
            try:
                sql_result = run_query(sql_query)
                print("\nSQL Query Result:")
                print(sql_result)
                logger.info(f"SQL Query Result: {sql_result}")
            except Exception as e:
                logger.error(f"Error executing SQL: {e}")
                sql_result = f"Error: {str(e)}"

            # Step 3: Get natural language answer
            answer = full_chain.invoke({"question": user_question}).content

        print("\nFinal Answer:")
        print(answer)

        # Clean up consumer after processing
        kafka_manager.disconnect_consumer(consumer_id)

finally:
    # Cleanup on exit
    kafka_manager.disconnect_all()
    logger.info("Gateway shutdown complete")


   
